all: a1_p1 a1_p2 a1_p3 a1_p4 a1_p5

a1_p1: a1_p1.cpp
	g++ -o a1_p1 a1_p1.cpp

a1_p2: testStack.cpp
	g++ -o testStack testStack.cpp

a1_p3: testLinkedList.cpp
	g++ -o testLinkedList testLinkedList.cpp

a1_p4: a1_p4.cpp
	g++ -o a1_p4 a1_p4.cpp

a1_p5: a1_p5.cpp
	g++ -o a1_p5 a1_p5.cpp