all: a7_p1a a7_p1b a7_p1c a7_p1d a7_p2a a7_p2c

a7_p1a: a7_p1a.cpp
	g++ -o a7_p1a a7_p1a.cpp

a7_p1b: a7_p1b.cpp
	g++ -o a7_p1b a7_p1b.cpp

a7_p1c: a7_p1c.cpp
	g++ -o a7_p1c a7_p1c.cpp

a7_p1d: a7_p1d.cpp
	g++ -o a7_p1d a7_p1d.cpp

a7_p2a: a7_p2a.cpp
	g++ -o a7_p2a a7_p2a.cpp

a7_p2c: a7_p2c.cpp
	g++ -o a7_p2c a7_p2c.cpp