all: a2_p1 a2_p2 a2_p3 a2_p4 a2_p5 a2_p6

a2_p1: a2_p1.cpp
	g++ -o a2_p1 a2_p1.cpp

a2_p2: a2_p2.cpp
	g++ -o a2_p2 a2_p2.cpp

a2_p3: WindGauge.cpp testWindGauge.cpp
	g++ -o testWindGauge WindGauge.cpp testWindGauge.cpp

a2_p4: a2_p4.cpp
	g++ -o a2_p4 a2_p4.cpp

a2_p5: a2_p5.cpp
	g++ -o a2_p5 a2_p5.cpp

a2_p6: a2_p6.cpp
	g++ -o a2_p6 a2_p6.cpp